### PR TITLE
Add lint tests for all the lint checks

### PR DESCRIPTION
**Pull request by punchagan**
- [x] Port existing tests from opam-repo-ci
- [x] Add tests for missing lint checks

### CODE REVIEW

**Review by shonfeder — APPROVED** [review]
LGTM!

I think it could be a nice improvement, down the way, to see if we can isolate the core logic away from the state of the git directory.  In that case, we might only need one check that the integration with git works as expected, and the rest of the tests could be simplified, and just focused on the logic of comparing file contents. 

Something we can maybe talk about later!

**Comment by punchagan** [comment]
I've added a few more tests to cover more of our lint checks. 

> I think it could be a nice improvement, down the way, to see if we can isolate the core logic away from the state of the git directory. In that case, we might only need one check that the integration with git works as expected, and the rest of the tests could be simplified, and just focused on the logic of comparing file contents.

Currently, the code doesn't really do anything with the state of the git repository. The tests look the way they look because they have been ported from the `opam-repo-ci` repo. They could possibly be simplified to get rid of the git repository manipulation. 

When we add functionality to automatically changed packages, the interaction with the git repository will really come into play. And yes, we could make sure the interaction with the git repo code is isolated from the core logic that runs the lint checks.

**Review by shonfeder — APPROVED** [review]
LGTM!

**Comment by shonfeder** [comment]
As a followup, I think we can likely come up with a more streamlined testing strategy (and making the core linting logic pure would help here), but as an incremental step to migrating the logic out of the CI pipeline, this is excellent.

**Comment by punchagan** [comment]
> As a followup, I think we can likely come up with a more streamlined testing strategy (and making the core linting logic pure would help here), but as an incremental step to migrating the logic out of the CI pipeline, this is excellent.

Thanks for the review. I agree we could work on improving the testing strategy! We can do it as a follow up.

**Pull request merged**
